name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Snake Animation
      #- uses: Platane/snk@master
      #  id: snake-gif
      #  with:
      #    github_user_name: Hobbies-Prof-Bento
      #    svg_out_path: dist/github-contribution-grid-snake.svg
      
      - name: generate SVGs
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: YurgenSchn
          outputs: |
            dist/commit-snake.svg
            dist/commit-snake-dark.svg?palette=github-dark
            dist/commit-snake-dark-orange.svg?palette=github-dark&color_snake=orange

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
